config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :locations
  get '/locations', to: 'locations#index'
  post '/locations', to: 'locations#create', as: 'new_location'
  delete '/locations', to: 'locations#delete_all', as: 'delete_all_locations'
  root to: "locations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :authenticate_user!, :except => [:index]
  # GET /locations
  def index
    if user_signed_in?
      gon.locations = current_user.locations
      # @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      #   marker.lat location.latitude
      #   marker.lng location.longitude
      # end
    end
  end

  # POST /locations
  def create
    respond_to do |format|
      if user_signed_in?
        @location = current_user.locations.new(location_params)
        if @location.save
          format.html {redirect_to action: "index", notice: 'Location was successfully created.'}
        else
          format.html {redirect_to action: "index", notice: 'Location was not created.'}
        end
      end
    end
  end

  # DELETE /locations
  def delete_all
    current_user.locations.delete_all
    puts "Se borraron todas sus locations"
  end

  # GET /locations/
  def my_locations
    if user_signed_in?
      return current_user.locations
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<%= csrf_meta_tag %><!DOCTYPE html>
<html>
  <head>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <title>Maps1</title>
    <!-- para pasar datos a javascript -->
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2t8xnBAzRvitlkKz0nVe6HqSQawsUq9g&callback=initMap">
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyD2t8xnBAzRvitlkKz0nVe6HqSQawsUq9g"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<% if user_signed_in? %>
  <button type="button" id="btn_new_location">Start tracking</button>
  <button type="button" id="btn_stop_tracking">Stop tracking</button>
  <%= button_to 'Delete All Locations', delete_all_locations_path, method: :delete %>
  <div style='width: 800px;'>
    <div id="directions" style='width: 800px; height: 400px;'></div>
  </div>
<%else%>
  <h3>Debe iniciar sesión para visualizar una ruta.</h3>
  <%= link_to 'Iniciar sesión', new_user_session_path, method: :get %>
<%end%>